# ?????
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis??
mybatis.mapper-locations=classpath*:mapper/*.xml
mybatis.type-aliases-package=com.qtc.ecommerce_demo.entity
mybatis.configuration.map-underscore-to-camel-case=true
# ?????MyBatis??????
# mybatis.config-location=classpath:mybatis-config.xml

# SQL????
logging.level.com.qtc.ecommerce_demo.mapper=TRACE
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.mybatis=DEBUG

# ????
spring.application.name=ecommerce_demo
server.port=8081